In [2]:
import numpy as np

In [4]:
a = np.array([[1.,0.,0.],[0.,0.7882,-0.6154],[0.,0.6154,0.7882]])
b = np.array([[1.,-1.,0.],[-1.,2.,2.],[0.,2.,3.]])
c = a.T

In [15]:
a = np.array([[4., -1. ,1.],[16., -2., -3.],[16., -3., -1.]])
I = np.array([[1, 0, 0], [0, 1, 0] ,[0, 0, 1]])
H1 = I - np.array([[360.1739953,-303.6520094, -303.6520094],[-303.6520094, 256., 256.], [-303.6520094, 256., 256.]])/436.0869977
H2 = H1@a

In [16]:
H1

array([[ 0.17407766,  0.69631062,  0.69631062],
       [ 0.69631062,  0.41296117, -0.58703883],
       [ 0.69631062, -0.58703883,  0.41296117]])

In [14]:
print(H1@a)

[[ 2.29782506e+01 -3.65563078e+00 -2.61116484e+00]
 [ 1.83449522e-09  2.38883516e-01  4.44659355e-02]
 [ 1.83449522e-09 -7.61116484e-01  2.04446594e+00]]


In [18]:
H2 

array([[ 2.29782506e+01, -3.65563078e+00, -2.61116484e+00],
       [ 1.83449522e-09,  2.38883516e-01,  4.44659355e-02],
       [ 1.83449522e-09, -7.61116484e-01,  2.04446594e+00]])

In [29]:
K = np.array([[0.312,0.4251],[0.4251, 0.579121]])/0.445604294

In [21]:
A2 = np.array([[0.239, 0.044],[-0.761, 2.044]])

In [30]:
K = np.array([[1,0],[0,1]])-K;

In [31]:
K 

array([[ 0.29982721, -0.95398542],
       [-0.95398542, -0.29963065]])

In [32]:
K@A2

array([[ 7.97641609e-01, -1.93675380e+00],
       [ 1.64120187e-05, -6.54420415e-01]])